### ISSUE TITLE
Tray icon option to match KDE Plasma 5 and add custom name?

### ISSUE THREAD

**Issue by ghtesting2020** [x211321/RGB-Config-Acer-gkbbl-0#1]
Hi, thank you for creating this GUI for Acer RGB it is very cool.

Is it possible for you to add an option so the tray icon can either be 1) multicolored like it is now or 2) all white so it matches other KDE Plasma icons? Currently out of my sons 8-9 tray icons, this is the only one with color and sticks out like a sore thumb haha.

Here is example of current KDE Plasma tray icons, and then we get RGB disco from this one haha.

![trayicons](https://user-images.githubusercontent.com/69682350/209607145-911cb839-72f9-42fb-acbe-d33b76e6778c.png)

Is it also possible to rename the tray icon? Currently when the name and when hover it says "rgb_config_acer_gkbbl_0.py" very loooong. Maybe something like "Acer RGB Config" or "Acer RGB"?

either way thank you again this GUI is exactly what we needed, very cool 10/10! I bought this laptop for my son Christmas and he loves it. It suck how Acer did not make a native GUI RGB for Linux.

**Comment by x211321** [comment]
Hi, thank you for your feedback. 

I've added an option for selecting different tray icon styles. You can now choose between the default RGB icon or two different outline-only icons (black and white). 

![trayiconstyle](https://user-images.githubusercontent.com/49248821/209676989-3386fb6b-680e-4499-8d09-b011f01bc670.png)

There is not a lot I can do about your other request regarding the icon text. This seems to be a [bug](https://github.com/wxWidgets/wxWidgets/issues/18081) in wxWidgets and/or KDE Plasma for which I have not been able to find a workaround for. 

Another framework related issue seems to be the general [blurriness](https://github.com/wxWidgets/wxWidgets/issues/19048
) of the icon when displayed in the system tray. 

I find both issues somewhat annoying but they are sadly beyond my control. 

Again, thanks for your feedback. Let me know if these changes work for you.

**Comment by ghtesting2020** [comment]
Thank you! Yes it looks much more uniform now that my son can make the icon white.

**Comment by ghtesting2020** [comment]
Hi @x211321 i ended up asking the wxPython team and they suggested this for the blurry icons:
"Presumably you are using a HiDPI display? It is likely in that case that your application needs to be updated to use ```wx.BitmapBundle``` to provide different icon sizes that will be used."
https://github.com/wxWidgets/Phoenix/issues/2324

does this help or were you already using ```wx.BitMapBundle``` and different icon sizes? My sons screen is set to 96 dpi but screen resolution is 1920x1080 (16:9).

**Comment by x211321** [comment]
Hi, thanks for coming back with additional info. 

I gave wx.BitMapBundle a try before but did not find notable improvements. Maybe I did something wrong but my initial tests did not convince me. 

I might give it another go. Will report my findings if I do.

**Comment by x211321** [comment]
I took some time tinkering with different icon sizes both as individual icons and as bitmap bundles and by now I'm quite certain that the blurriness is not caused by me not using wx.BitMapBundle. 

Neither of us appears to be using HiDPI displays thus providing different icon sizes in our specific case should make no difference. No matter how many different icon sizes I provide the result is always blurry. The only thing that is making somewhat of a difference is providing the Icons with less complexity and at an initial resolution that's more to the liking of the KDE tray.

As far as I can see all a wx.BitMapBundle provides is a selection of icon sizes depending on the HiDPI scale factor. E.g. if your scaling is set to 2x wxPython will use the second Icon of the bundle or interpolate a new Icon in case of fractional scale factors. 

In general it does seem like a good idea to use this technique but it doesn't appear to help with this issue in particular.

In the end I'm by no means an expert about any of this so my conclusion could still be wrong but at this point I don't think I will spend any more time on the icon situation. For now I've included additional Icons with square corners which look a little less blurry.

![image](https://user-images.githubusercontent.com/49248821/209995863-8c0520fb-9638-4093-b8dd-07aa657e7cf9.png)

It's not great but will have to do for now. I'll provide a new release later today. 

As a side note: I have been working on a native plasma widget version of this app for a while now. Maybe I can find the time to finish that one at some point. This would hopefully bypass all the current issues with the KDE tray. 

![image](https://user-images.githubusercontent.com/49248821/209996252-8ffacbca-b510-4719-aff9-aee412763a9b.png)

Again thank you for your feedback. I hope you and your son will continue to find use in this little project.

**Comment by ghtesting2020** [comment]
Thank you very much for looking into it further and all of your hard work. Yes it does look less blurry now. I guess this will have to do :+1:

**Comment by x211321** [comment]
@ghtesting2020 

I put some work into the plasma widget version and now have something that seems to work. 

Its still early in development and hasn't been tested a whole lot but the repo is up and I added a first release. 

The plasma widget version has less features (e.g. no profiles, etc.) but on the plus side it integrates seamlessly into KDE.

Might give it a look if you or your son are interested. I'm always in search of feedback. 

https://github.com/x211321/RGB-Config-Acer-gkbbl-0-Plasma-Widget
