### ISSUE TITLE
no longer work

### ISSUE THREAD

**Issue by ghtesting2020** [x211321/RGB-Config-Acer-gkbbl-0#2]
Hello there we were really enjoying the software but in latest arch updates it no longer works. When trying to hit Apply for a profile it says RGB Device /dev/acer-gkbbl-0 not available :( can you please help?

**Comment by x211321** [comment]
Hi, when the device is not available it means that the kernel module (basically the driver) is either not installed or not loaded. This often happens after a kernel update and is usually fixed by reinstalling (and therefore recompiling) the kernel module. Please refer to the project page of the kernel module for more information https://github.com/JafarAkhondali/acer-predator-turbo-and-rgb-keyboard-linux-module in their bug tracker you can find multiple similar threads like this one for example https://github.com/JafarAkhondali/acer-predator-turbo-and-rgb-keyboard-linux-module/issues/113 . Once the module has been reinstalled RGB Config should work again. 

A simple way that usually fixes this problem is to download the above mentioned repository, then run the uninstall script followed by the install_service script. You might need to reboot afterwards.

Hope that helps. Feel free to get back to me if something is not clear.

**Comment by ghtesting2020** [comment]
thank you so much it works
